sysmap/sysmap/urls.py
from django.contrib import admin
from django.urls import path, include
from contracts import views
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers
from contracts.views import ContractViewset, HolderViewset
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

import authentication.views, execution.views

router = routers.SimpleRouter()
router.register('contracts', ContractViewset, basename='contract')
router.register('holder', HolderViewset, basename='holder')

urlpatterns = [
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('admin/', admin.site.urls),

    path('', authentication.views.login_page, name='login'),
    path('logout/', authentication.views.logout_user, name='logout'),
    path('welcome/', views.welcome, name='home'),
    path('contracts/', views.contract_list, name='contract-list'),
    path('contract/<int:id>', views.contract_detail, name='contract-detail'),
    path('contract/<int:id>/update', views.contract_update, name='contract-update'),
    path('contract/<int:id>/disable', views.contract_disable, name='contract-disable'),
    path('contract/<int:id>/print', views.contract_print, name='contract-print'),
    path('contract/add', views.contract_create, name='contract-create'),
    path('contract/<int:id>/amount', views.contract_amount, name='contract-add-amount'),
    path('contract/<int:id1>/<int:id2>/upd-amount', views.contract_upd_amount, name='contract-upd-amount'),
    path('contract/<int:id>/finance', views.contract_finance, name='contract-add-finance'),
    path('contract/<int:id1>/<int:id2>/upd-finance', views.contract_upd_finance, name='contract-upd-finance'),
    path('contract/<int:id>/holder', views.contract_holder, name='contract-add-holder'),
    path('contract/<int:id>/commission', views.contract_commission, name='contract-add-commission'),
    path('contract/<int:id>/follow-tech', execution.views.follow_tech_contract, name='follow-tech-contract'),
    path('contract/<int:id>/follow-fi', execution.views.follow_fi_contract, name='follow-fi-contract'),
    path('event/<int:id>/add-livrable', execution.views.create_livrable, name='event-add-livrable'),
    path('contract/<int:id>/add-event', execution.views.create_event, name='suivi-add-event'),
    path('event/<int:id>/add-ordre-service', execution.views.create_ordre_service, name='event-add-ordre-service'),
    path('event/<int:id>/add-avenant', execution.views.create_avenant, name='event-add-avenant'),
    path('event/<int:id>/event-detail', execution.views.event_detail, name='event-detail'),
    path('contract/<int:id>/add-decompte', execution.views.create_decompte, name='contract-add-decompte'),
    path('contract/<int:id>/add-paiement', execution.views.create_paiement, name='contract-add-paiement'),
    path('contract/<int:id>/decompte-detail', execution.views.decompte_detail, name='decompte-detail'),
    path('contract/generate', views.generate_pdf, name='generate-pdf'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root = settings.MEDIA_ROOT
    )

sysmap/contracts/models.py
from django.conf import settings
from django.db import models

class Holder(models.Model):
    raisonSociale = models.fields.CharField(max_length=100)
    representant = models.fields.CharField(max_length=100, default="inconnu")
    poBox = models.fields.CharField(max_length=20, null=True)
    phone = models.fields.CharField(max_length=15, null=True)
    numContribuable = models.fields.CharField(max_length=20)
    compteBancaire = models.fields.CharField(max_length=50)
        
    def __str__(self):
        desc = str(self.raisonSociale)
        return desc

class Montant(models.Model):
    mtHtax = models.fields.IntegerField(default=0)
    mtTva = models.fields.FloatField(blank=True, null=True)
    mtAir = models.fields.FloatField(blank=True, null=True)
    mtNet = models.fields.FloatField(blank=True, null=True)
    mtTtc = models.fields.FloatField(blank=True, null=True)

    def __str__(self):
        return str(self.mtTtc)

class CommissionMember(models.Model):
    designation = models.fields.CharField(max_length=60, null=True)
    sigle = models.fields.CharField(max_length=10)

    def __str__(self):
        desc = str(self.designation)+': '+ str(self.sigle)
        return str(desc)

class Ressource(models.Model):
    source = models.fields.CharField(max_length=50, default="BUDGET D'INVESTISSEMENT PUBLIC")
    code = models.fields.CharField(max_length=5, default="BIP")
    
    def __str__(self):
        return str(self.source)

class Guichet(models.Model):
    source = models.ForeignKey(Ressource, on_delete=models.CASCADE)
    guichet = models.fields.CharField(max_length=30, default="Paierie Générale du Trésor")
    imputation = models.fields.CharField(max_length=27, null=True)

    def __str__(self):
        return str(self.imputation)

class Localization(models.Model):
    localite = models.fields.CharField(max_length=15, blank=True)

    def __str__(self):
        return f'self.localite'

class Cautionnement(models.Model):
    taux = models.fields.IntegerField()
    garant = models.fields.CharField(max_length=15)
    situation = models.fields.BooleanField(default=False)

    def __str__(self):
        return f'self.garant'

class Exercice(models.Model):
    annee = models.fields.IntegerField()
    codeExo = models.fields.IntegerField(null=True, blank=True)
    tauxTva = models.fields.FloatField(null=True, default=19.25)
    tauxIR = models.fields.FloatField(null=True, default=2.2)
    autreTax = models.fields.FloatField(null=True, blank=True)
    def __str__(self):
        return str(self.annee)
   
class Contract(models.Model):
    class Chapitre(models.TextChoices):
        INTERVENTION_EN_INVESTISSEMENT = "94"
        ECONOMIE_PLANIFICATION_ET_AMENAGEMENT_DU_TERRITOIRE = "22"
    chapitre = models.fields.CharField(choices=Chapitre.choices, max_length=2, default="22")
    object = models.fields.CharField(max_length=200)
    numero = models.fields.CharField(max_length=50, blank=True)
    delays = models.fields.IntegerField(null=True)
    souscriptionDate = models.fields.DateField(null=True, blank=True)
    lieuLivraison = models.fields.CharField(max_length=100)
    actif = models.fields.BooleanField(default=True)
    consistancy = models.fields.CharField(max_length=300, null=True)
    revisionPrice = models.fields.BooleanField(default=False, blank=True)
    storedTaxation = models.fields.BooleanField(default=True)
    urgencyProcess = models.fields.BooleanField(default=False)
    datSignaMoa = models.fields.DateField(null=True, blank=True)
    numLot = models.fields.IntegerField(null=True, default=0)
    authorCo = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    dateCreated = models.DateField(auto_now=True, null=True)
    holder = models.ForeignKey(Holder, null=True, blank=True, on_delete=models.SET_NULL)
    montant = models.ForeignKey(Montant, null=True, blank=True, on_delete=models.SET_NULL)
    commission = models.ManyToManyField(CommissionMember, through='MembersCommission')
    financement = models.ForeignKey(Guichet, null=True, blank=True, on_delete=models.SET_NULL)
    localization = models.ForeignKey(Localization, null=True, blank=True, on_delete=models.SET_NULL)
    caution = models.ForeignKey(Cautionnement, null=True, blank=True, on_delete=models.SET_NULL)
    exercices = models.ManyToManyField(Exercice)
    class UniteDelai(models.TextChoices):
        JOURS = 'JR'
        MOIS = 'M'
    uniteDelai = models.fields.CharField(choices=UniteDelai.choices, max_length=2, default='M')
    class TypePassation(models.TextChoices):
        APPEL_OFFRE_NATIONAL_OUVERT = 'AONO'
        APPEL_OFFRE_NATIONAL_RESTREINT = 'AONR'
        PROCEDURE_ACCORD_CADRE = 'AC'
        APPEL_OFFRE_INTERNATIONAL_OUVERT = 'AOIO'
        APPEL_OFFRE_INTERNATIONAL_RESTREINT = 'AOIR'
        APPEL_OFFRE_NATIONAL_CONCOURS = 'AONC'
        APPEL_OFFRE_INTERNATIONAL_CONCOURS = 'AOIC'
        APPEL_OFFRE_2_ETAPES = 'AO2'
        PROCEDURE_GRE_A_GRE = 'GAG'
        PROCEDURE_DEMANDE_COTATION = 'DC'
        PROCEDURE_DE_CONSULTATION_INDIVIDUELLE = 'CI'
    typePassation = models.fields.CharField(choices=TypePassation.choices, max_length=5, default= 'AONO')
    numeroPassation = models.fields.CharField(max_length=100, default="inconnu")

    def __str__(self):
        desc = str(self.object)
        return desc

    def disable(self):
        if self.actif is False:
            return
        self.actif = False
        self.save()
        

class MembersCommission(models.Model):
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)
    commissionMember = models.ForeignKey(CommissionMember, on_delete=models.CASCADE)
    class Role(models.TextChoices):
        PRESIDENT = "PR"
        CHEF_SERVICE_MARCHE = "CSM"
        INGENIEUR = "ING"
        COMPTABLE = "CM"
        INGENIEUR_SUIVI = "INS"
        AUTRE = "AUT"
    role = models.fields.CharField(choices=Role.choices, max_length=3, default="ING")

    class Meta:
        unique_together = ('contract', 'commissionMember')
    
    def __str__(self):
        desc = str(self.role)
        return desc

sysmap/contracts/forms.py
from django import forms
from contracts.models import Contract, Montant, Guichet, Holder, MembersCommission

class ContractForm(forms.ModelForm):
    object = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control form-control-contract', 'placeholder':'Objet du contrat :'}), label='')
    numero = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Numéro du contrat'}), label='')
    delays = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder':'Délai'}), label='')
    lieuLivraison = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control form-control-user', 'placeholder':'Lieu de livraison...'}), label='')
    consistancy = forms.CharField(max_length=300, required=False, widget=forms.Textarea(attrs={'class': 'form-control form-control-user', 'placeholder':'Consistence...',}), label='')
    revisionPrice = forms.BooleanField(required=False, widget=forms.CheckboxInput, label='Contrat soumis au régime de révision des prix?')
    storedTaxation = forms.BooleanField(required=False, widget=forms.CheckboxInput, label='Contrat Enregistré?')
    urgencyProcess = forms.BooleanField(required=False,widget=forms.CheckboxInput, label='En procédure d urgence?')
    numLot = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={'class': 'form-control'}), label='Numero de lot')
    souscriptionDate = forms.DateField(required=False, widget=forms.NumberInput(attrs={'class':'form-control', 'type' : 'Date', 'placeholder':'Select a date...'}), label='Date de la Souscription')
    datSignaMoa = forms.DateField(required=False, widget=forms.NumberInput(attrs={'class':'form-control', 'type' : 'Date', 'placeholder':'Select a date...'}), label='Date de signature par le MOA')
    numeroPassation = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Numéro appel d offre'}), label='')
    class Meta:
        model = Contract
        fields = ['typePassation', 'object', 'numero','delays', 'uniteDelai', 'lieuLivraison', 'consistancy', 
                  'revisionPrice', 'storedTaxation', 'numLot', 'souscriptionDate', 'datSignaMoa', 'exercices', 
                  'numeroPassation', 'urgencyProcess', 'chapitre']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['typePassation'].widget.attrs.update({'class': 'form-control'})
        self.fields['uniteDelai'].widget.attrs.update({'class': 'form-control'})
        self.fields['typePassation'].label = ''
        self.fields['uniteDelai'].label = ''
        self.fields['souscriptionDate'].widget.attrs.update({'class': 'form-control'})
        self.fields['exercices'].widget.attrs.update({'class': 'form-control'})
        self.fields['chapitre'].widget.attrs.update({'class': 'form-control'})
        


class MontantForm(forms.ModelForm):
    class Meta:
        model = Montant
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['mtHtax'].widget.attrs.update({'class': 'form-control'})
        self.fields['mtHtax'].label = 'Montant HT'
        self.fields['mtTva'].widget.attrs.update({'class': 'form-control'})
        self.fields['mtTva'].label = 'Montant TVA'
        self.fields['mtAir'].widget.attrs.update({'class': 'form-control'})
        self.fields['mtAir'].label = 'Montant IR'
        self.fields['mtNet'].widget.attrs.update({'class': 'form-control'})
        self.fields['mtNet'].label = 'Montant Net'
        self.fields['mtTtc'].widget.attrs.update({'class': 'form-control'})
        self.fields['mtTtc'].label = 'Montant TTC'
    
class GuichetForm(forms.ModelForm):
    class Meta:
        model = Guichet
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['source'].widget.attrs.update({'class': 'form-control'})
        self.fields['source'].label = 'Nature des ressources'
        self.fields['guichet'].widget.attrs.update({'class': 'form-control'})
        self.fields['guichet'].label = 'Guichet ou Banque de paiement'
        self.fields['imputation'].widget.attrs.update({'class': 'form-control'})
        self.fields['imputation'].label = 'Imputation'

class HolderForm(forms.ModelForm):
    raisonSociale = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Raison Sociale :'}), label='Raison sociale')
    poBox = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Boite postale :'}), label='Boite postale')
    phone = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Numéro de téléphone :'}), label='Téléphone')
    numContribuable = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}), label='Numéro de contribuable')
    compteBancaire = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}), label='Numéro du compte bancaire')
    representant = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}), label='Représentant de l entreprise')
    
    class Meta:
        model = Holder
        fields = '__all__'

""" class CommissionForm(forms.ModelForm):
    president = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Président :'}), label='Président')
    csm = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}), label='Chef de Service')
    engineer = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}), label='Ingénieur')
    comptable = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}), label='Comptable-Matières')
    
    class Meta:
        model = Commission
        fields = '__all__'
 """

class MembersCommissionForm(forms.ModelForm):
    class Meta:
        model = MembersCommission
        fields = ['commissionMember', 'role']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['commissionMember'].widget.attrs.update({'class': 'form-control'})
        self.fields['role'].widget.attrs.update({'class': 'form-control'})

sysmap/contracts/templates/contracts/contract_add_commission.html
{% extends 'contracts/base.html' %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800"> AJOUT ELEMENT DU MARCHE / CONTRAT</h1>
    </div>
    <div class="row"> 
        <div class="col-sm-4">
            {% include "contracts/contract_summary.html" %}
        </div>
        <div class="col-sm-8">         
            <!-- Basic Card Example -->
            <div class="card shadow mb-4">
                <div class="card-body">
                    <h6 class="m-0 font-weight-bold text-primary"> AJOUT DES INFORMATIONS SUR LA COMMISSION DE RECETTE DU MARCHE:</h6>
                    <form action="" method="POST" novalidate>
                        {% csrf_token %}
                        {{ formset.as_p }}
                        <button type="submit" class="btn btn-primary btn-block">Enregistrer</button>        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-sm-4">
    <p>
        <a href="{% url 'contract-detail' contract.id %}" class="btn btn-primary btn-block">Retour à la fiche descriptive du contrat</a>
    </p>
</div>

{% endblock %}

sysmap/contracts/templates/contracts/contract_detail.html
{% extends 'contracts/base.html' %}
{% load l10n %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    
    <div class="row">
        <div class="col-sm-4">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800"> DETAILS DESCRIPTIFS DU MARCHE </h1>
            </div>
        </div>
        <div class="col-sm-2">
            <a href="{% url 'contract-list' %}" class="btn btn-primary btn-block">Liste des contrats</a>
        </div>
        <div class="col-sm-2">
            <a href="{% url 'contract-create' %}" class="btn btn-primary btn-block">Nouveau Marché</a>
        </div>
        <div class="col-sm-2">
            <a href="{% url 'follow-tech-contract' contract.id %}" class="btn btn-primary btn-block">Suivi Technique</a>
        </div>
        <div class="col-sm-2">
            <a href="{% url 'follow-fi-contract' contract.id %}" class="btn btn-primary btn-block">Suivi Financier</a>
        </div>   
           
    </div>
    <div class="row"> 
        <div class="col-sm-4">
            {% include "contracts/contract_summary.html" %}
                                <!-- Basic Card Example -->
                                <!-- <div class="card shadow mb-4">
                                    <div class="card-body">
                                        {% if contract.localization %}
                                        <h6 class="m-0 font-weight-bold text-primary">LOCALITE</h6>
                                        <h6 class="m-0 font-weight-bold text-primary"> ARRONDISSEMENT :</h6><p>{{ contract.localization }}</p>
                                        <h6 class="m-0 font-weight-bold text-primary"> DEPARTEMENT: </h6><p>{{ contract.localization  }}</p>
                                        <h6 class="m-0 font-weight-bold text-primary"> REGION: </h6><p>{{ contract.localization  }}</p>
                                        {% else %} PAS D'INFORMATIONS {% endif %}
                                    </div>
                                </div> -->
        </div>

        <div class="col-sm-4">
            <!-- Dropdown Card Example -->
            <div class="card shadow mb-4">         
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">MONTANTS</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                            aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Actions</div>
                            {% if contract.montant %}
                            <a class="dropdown-item" href="{% url 'contract-upd-amount' contract.id contract.montant.id %}">Modifier</a>
                            {% else %}
                            <a class="dropdown-item" href="{% url 'contract-add-amount' contract.id %}">Ajouter</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="card-body">        
                    {% if contract.montant %}
                    <h6> MONTANT HT: <span class="m-0 font-weight-bold text-primary">{{ contract.montant.mtHtax }}</span></h6>
                    <h6> MONTANT TVA: <span class="m-0 font-weight-bold text-primary">{{ contract.montant.mtTva }}</span></h6>
                    <h6> MONTANT AIR: <span class="m-0 font-weight-bold text-primary">{{ contract.montant.mtAir }}</span></h6>
                    <h6> MONTANT NET: <span class="m-0 font-weight-bold text-primary">{{ contract.montant.mtNet }}</span></h6>
                    <hr class="sidebar-divider">
                    <h6> MONTANT TTC: <span class="m-0 font-weight-bold text-danger">{{ contract.montant.mtTtc }}</span></h6>
                    {% else %} PAS D'INFORMATIONS {% endif %}
                </div>
            </div>

            <!-- Dropdown Card Example -->
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">FINANCEMENT</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                            aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Actions</div>
                            {% if contract.financement %}
                            <a class="dropdown-item" href="{% url 'contract-upd-finance' contract.id contract.financement.id %}">Modifier</a>
                            {% else %}
                            <a class="dropdown-item" href="{% url 'contract-add-finance' contract.id %}">Ajouter</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    {% if contract.financement %}
                    <h6> SOURCE: <span class="m-0 font-weight-bold text-primary">{{ contract.financement.get_source_display }}</span></h6>
                    <h6> GUICHET: <span class="m-0 font-weight-bold text-primary">{{ contract.financement.guichet }}</span></h6>
                    <hr class="sidebar-divider">
                    <h6> IMPUTATION: <span class="m-0 font-weight-bold text-primary">{{ contract.financement.imputation }}</span></h6>
                    {% else %} PAS D'INFORMATIONS {% endif %}
                </div>
            </div>
        </div>
 
        <div class="col-sm-4">

            <!-- Dropdown Card Example -->
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">TITULAIRE</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                            aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Actions</div>
                            {% if contract.holder %}
                            <a class="dropdown-item" href="{% url 'contract-add-holder' contract.id %}">Modifier</a>
                            {% else %}
                            <a class="dropdown-item" href="{% url 'contract-add-holder' contract.id %}">Ajouter</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    {% if contract.holder %}
                    <h6> RAISON SOCIALE: <span class="m-0 font-weight-bold text-danger">{{ contract.holder.raisonSociale }}</span></h6>
                    <h6> REPRESENTE PAR: <span class="m-0 font-weight-bold text-primary">{{ contract.holder.representant }}</span></h6>
                    <hr class="sidebar-divider">
                    <h6> BOITE POSTALE: <span class="m-0 font-weight-bold text-primary">{{ contract.holder.poBox }}</span></h6>
                    <h6> TELEPHONE: <span class="m-0 font-weight-bold text-primary">{{ contract.holder.phone }}</span></h6>
                    <h6> NUMERO CONTRIBUABLE: <span class="m-0 font-weight-bold text-primary">{{ contract.holder.numContribuable }}</span></h6>
                    <h6> COMPTE BANCAIRE: <span class="m-0 font-weight-bold text-primary">{{ contract.holder.compteBancaire }}</span></h6>
                    {% else %} PAS D'INFORMATIONS {% endif %}
                </div>
            </div>

                        <!-- Dropdown Card Example -->
                        <div class="card shadow mb-4">
                            <!-- Card Header - Dropdown -->
                            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                <h6 class="m-0 font-weight-bold text-primary">COMMISSION DE RECETTE</h6>
                                <div class="dropdown no-arrow">
                                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                                        aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                                        <div class="dropdown-header">Actions</div>
                                       
                                        {% if contract.commission %}
                                        <a class="dropdown-item" href="{% url 'contract-add-commission' contract.id %}">Modifier</a>
                                        {% else %}
                                        <a class="dropdown-item" href="{% url 'contract-add-commission' contract.id %}">Ajouter</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <!-- Card Body -->
                            <div class="card-body">
                                {% if contract.commission %}
                                {% for member in contract.commission.all %} 
                                    {% for membre in member.memberscommission_set.all %} {% if membre.role == "PR" and membre.contract == contract %} 
                                        <h6> PRESIDENT: <span class="m-0 font-weight-bold text-primary">{{ membre.commissionMember }} {% endif %} {% endfor %}</span></h6>
                                    {% for membre in member.memberscommission_set.all %} {% if membre.role == "CSM" and membre.contract == contract %} 
                                        <h6> CHEF DE SERVICE: <span class="m-0 font-weight-bold text-primary">{{ membre.commissionMember }} {% endif %} {% endfor %}</span></h6>
                                    {% for membre in member.memberscommission_set.all %} {% if membre.role == "ING" and membre.contract == contract %} 
                                        <h6> INGENIEUR: <span class="m-0 font-weight-bold text-primary">{{ membre.commissionMember }} {% endif %} {% endfor %}</span></h6>
                                    {% for membre in member.memberscommission_set.all %} {% if membre.role == "CM" and membre.contract == contract %} 
                                    <h6> COMPTABLE-MATIERES: <span class="m-0 font-weight-bold text-primary"> {{ membre.commissionMember }} {% endif %} {% endfor %}</span></h6>
                                {% endfor %}
                                {% else %} PAS D'INFORMATIONS {% endif %}
                            </div>
                        </div>
        </div>

    </div>
</div>

{% endblock %}