sysmap/sysmap/urls.py
from django.contrib import admin
from django.urls import path, include
from contracts import views
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers
from contracts.views import ContractViewset, HolderViewset
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

import authentication.views, execution.views

router = routers.SimpleRouter()
router.register('contracts', ContractViewset, basename='contract')
router.register('holder', HolderViewset, basename='holder')

urlpatterns = [
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('admin/', admin.site.urls),

    path('', authentication.views.login_page, name='login'),
    path('logout/', authentication.views.logout_user, name='logout'),
    path('welcome/', views.welcome, name='home'),
    path('contracts/', views.contract_list, name='contract-list'),
    path('contract/<int:id>', views.contract_detail, name='contract-detail'),
    path('contract/<int:id>/update', views.contract_update, name='contract-update'),
    path('contract/<int:id>/disable', views.contract_disable, name='contract-disable'),
    path('contract/<int:id>/print', views.contract_print, name='contract-print'),
    path('contract/add', views.contract_create, name='contract-create'),
    path('contract/<int:id>/amount', views.contract_amount, name='contract-add-amount'),
    path('contract/<int:id1>/<int:id2>/upd-amount', views.contract_upd_amount, name='contract-upd-amount'),
    path('contract/<int:id>/finance', views.contract_finance, name='contract-add-finance'),
    path('contract/<int:id1>/<int:id2>/upd-finance', views.contract_upd_finance, name='contract-upd-finance'),
    path('contract/<int:id>/holder', views.contract_holder, name='contract-add-holder'),
    path('contract/<int:id>/commission', views.contract_commission, name='contract-add-commission'),
    path('contract/<int:id>/follow-tech', execution.views.follow_tech_contract, name='follow-tech-contract'),
    path('contract/<int:id>/follow-fi', execution.views.follow_fi_contract, name='follow-fi-contract'),
    path('event/<int:id>/add-livrable', execution.views.create_livrable, name='event-add-livrable'),
    path('contract/<int:id>/add-event', execution.views.create_event, name='suivi-add-event'),
    path('event/<int:id>/add-ordre-service', execution.views.create_ordre_service, name='event-add-ordre-service'),
    path('event/<int:id>/add-avenant', execution.views.create_avenant, name='event-add-avenant'),
    path('event/<int:id>/event-detail', execution.views.event_detail, name='event-detail'),
    path('contract/<int:id>/add-decompte', execution.views.create_decompte, name='contract-add-decompte'),
    path('contract/<int:id>/add-paiement', execution.views.create_paiement, name='contract-add-paiement'),
    path('contract/<int:id>/decompte-detail', execution.views.decompte_detail, name='decompte-detail'),
    path('contract/generate', views.generate_pdf, name='generate-pdf'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root = settings.MEDIA_ROOT
    )

sysmap/execution/models.py
from django.db import models
from django.conf import settings
from contracts.models import Contract, Montant

class Event(models.Model):
    libelle = models.fields.CharField(max_length=200)
    dateEvent = models.fields.DateField(null=True, blank=True)
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)
    authorEv = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        desc = str(self.libelle)+' du '+ str(self.dateEvent)
        return desc

    class Meta:
        ordering = ["dateEvent"]

class Livrable(models.Model):
    class Nature(models.TextChoices):
        FOURNITURES = 'FO'
        TRAVAUX = 'TR'
        SCES_QUANTIFIABLES = 'SQ'
        PRES_INTELLECTUELLE = 'PI'
        CONCEPT_REALISATION = 'CR'
        ACCORD_CADRE = 'AC'
        PLURIANNUEL_TRANCHE = 'PT'
        RESERVE = 'RE'
        SPECIAL = 'SP'
    nature = models.fields.CharField(choices=Nature.choices, max_length=2, default='TR')
    libelle = models.fields.CharField(max_length=200)
    class TypeLivrable(models.TextChoices):
        IMPREVU = 'I'
        ATTENDU = 'A'
    typeLivrable = models.fields.CharField(choices=TypeLivrable.choices ,max_length=1, default='A') 
    isRealized = models.fields.BooleanField(default=False)
    isReceive = models.fields.BooleanField(default=False)
    datValidation = models.fields.DateField(blank=True, null=True)
    event = models.ForeignKey(Event, null=True, on_delete=models.CASCADE)
    authorLi = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.libelle)


class ExecutionContrat(models.Model):
    class EtatExec(models.TextChoices):
        EN_COURS = 1
        NON_DEBUTE = 2
        EN_ARRET = 3
    etatExec = models.fields.IntegerField(choices=EtatExec.choices, default=2)
    txExecPhy = models.fields.IntegerField(null=True)
    nbreAvenant = models.fields.IntegerField(null=True)
    nbreDecompte = models.fields.IntegerField(null=True)
    nbreOs = models.fields.IntegerField(null=True)

class Avenant(models.Model):
    objetAvenant = models.fields.CharField(max_length=250)
    event = models.ForeignKey(Event, blank=True, null=True, on_delete=models.CASCADE)
    montant = models.ForeignKey(Montant, blank=True, on_delete=models.CASCADE)
    dateAvenant = models.fields.DateField(blank=True, null=True)
    authorAv = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        desc = str(self.objetAvenant)+ ' du '+ str(self.dateAvenant)
        return str(desc)

class Ordre_Service(models.Model):
    numerOs = models.fields.CharField(max_length=50, blank=True, null=True)
    motifOs = models.fields.CharField(max_length=250)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    datOs = models.fields.DateField(null=True, blank=True)
    class TypeOs(models.TextChoices):
        DEMARRAGE = 'D'
        SUSPENSION = 'S'
        REPRISE = 'R'
        TECHNIQUE = 'T'
        SUSPENSION_REPRISE = 'SR'
    typeOs = models.fields.CharField(max_length=2, choices=TypeOs.choices, default='D')
    authorOs = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        desc = str(self.get_typeOs_display())+ ' pour '+ str(self.motifOs)
        return str(desc)
 
class Decompte(models.Model):
     numero = models.fields.CharField(max_length=50)
     designation = models.fields.CharField(max_length=200)
     txDecompte = models.fields.IntegerField()
     datDecompte = models.fields.DateField(null=True, blank=True)
     datSignaCsm = models.fields.DateField(null=True, blank=True)
     datSignaIng = models.fields.DateField(null=True, blank=True)
     datSignaMoa = models.fields.DateField(null=True, blank=True)
     montant = models.ForeignKey(Montant, on_delete=models.CASCADE)
     contract = models.ForeignKey(Contract, on_delete=models.CASCADE)  
     authorDe = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)   

class Paiement(models.Model):
    numero = models.fields.CharField(max_length=20)
    class ModEngagement(models.TextChoices):
        BON_ENGAGEMENT = 'BON'
        DECISION_ENGAGEMENT = 'DEC'
    modEngagement = models.fields.CharField(choices=ModEngagement.choices, max_length=3, default="BON")
    datPaiement = models.fields.DateField(null=True, blank=True)
    class ModePaiement(models.TextChoices):
        VIREMENT = 'V'
        EN_ESPECES = 'E'
        INCONNU = 'I'
    modePaiement = models.fields.CharField(choices=ModePaiement.choices, max_length=2, default='I') 
    decompte = models.ForeignKey(Decompte, on_delete=models.CASCADE)
    authorPa = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)    
    
    def __str__(self):
        desc = str(self.get_modePaiement_display())+ ' du bon Numéro '+ str(self.numBonEnga)
        return str(desc)

sysmap/execution/forms.py
from django import forms
from execution.models import Livrable, Event, Ordre_Service, Avenant, Decompte, Paiement

class LivrableForm(forms.ModelForm):
    libelle = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}), label='Libelle :')
    isRealized = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-control'}), label='Livrable Réalisé ?:')
    isReceive = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-control'}), label='Livrable Receptionné ?:')
    datValidation = forms.DateField(widget=forms.NumberInput(attrs={'class':'form-control', 'type' : 'Date', 'placeholder':'Select a date...'}), label='Date de validation')
    class Meta:
        model = Livrable
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nature'].widget.attrs.update({'class': 'form-control'})
        self.fields['typeLivrable'].widget.attrs.update({'class': 'form-control'})
        self.fields['nature'].label = 'Nature'
        self.fields['typeLivrable'].label = 'Type de livrable'
        self.fields['event'].widget.attrs.update({'class': 'form-control'})
        self.fields['event'].label = 'Evènement'
    
class OrdreServiceForm(forms.ModelForm):
    class Meta:
        model = Ordre_Service
        fields = '__all__'

class AvenantForm(forms.ModelForm):
    class Meta:
        model = Avenant
        fields = '__all__'

class EventForm(forms.ModelForm):
    libelle = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}), label='Libelle :')
    dateEvent = forms.DateField(widget=forms.NumberInput(attrs={'class':'form-control', 'type' : 'Date', 'placeholder':'Select a date...'}), label='Date')
    
    class Meta:
        model = Event
        fields = ['libelle', 'dateEvent']

class DecompteForm(forms.ModelForm):
    class Meta:
        model = Decompte
        exclude = ['contract'] 

class PaiementForm(forms.ModelForm):
    class Meta:
        model = Paiement
        fields = '__all__'

sysmap/execution/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django import forms
from contracts.models import Contract
from execution.models import Event, Decompte, Livrable, Ordre_Service, Avenant, Paiement
from execution.forms import LivrableForm, EventForm, OrdreServiceForm, AvenantForm, DecompteForm, PaiementForm

@login_required
def follow_tech_contract(request, id):
    contract = Contract.objects.get(id=id)
    events = Event.objects.filter(contract=contract).order_by("dateEvent")
    dico_livrables = {}
    dico_ordres = {}
    dico_avenants = {}
    for event in events:
        livrables = Livrable.objects.filter(event=event)
        ordres_service = Ordre_Service.objects.filter(event=event)
        avenants = Avenant.objects.filter(event=event)
        if len(livrables) > 0:
            dico_livrables[event] = livrables
        if len(ordres_service) > 0:
            dico_ordres[event] = ordres_service
        if len(avenants) > 0:
            dico_avenants[event] = avenants
    
    context = {'events': events, 
               'contract': contract, 
               'dico_livrables': dico_livrables, 
               'dico_ordres': dico_ordres,
               'dico_avenants': dico_avenants,
               }

    return render(request,
                  'execution/follow_tech_contract.html',
                  context= context)

@login_required
def follow_fi_contract(request, id):
    contract = Contract.objects.get(id=id)
    decomptes = Decompte.objects.filter(contract=contract).order_by("datDecompte")
    dico_paiements = {}
    for decompte in decomptes:
        paiements = Paiement.objects.filter(decompte=decompte)
        if len(paiements) > 0:
            dico_paiements[decompte] = paiements
    
    context = {
               'contract': contract,
               'decomptes': decomptes, 
               'dico_paiements': dico_paiements, 
               }

    return render(request,
                  'execution/follow_fi_contract.html',
                  context= context)

@login_required
def create_event(request, id):
    contract = Contract.objects.get(id=id)
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid:
            event = form.save(commit=False)
            event.contract = contract
            event.authorEv = request.user
            event.save()
            return redirect('follow-tech-contract', contract.id)
    else:
        form = EventForm()

    return render(request,
                  'execution/contract_add_event.html',
                  {'form': form, 'contract':contract})

@login_required
def create_livrable(request, id):
    contract = Contract.objects.get(id=id)
    if request.method == 'POST':
        form = LivrableForm(request.POST)
        if form.is_valid:
            livrable = form.save(commit=False)
            livrable.authorLi = request.user
            livrable.save()
            return redirect('follow-tech-contract', contract.id)
    else:
        form = LivrableForm()
        form.fields['event'] = forms.ModelChoiceField(Event.objects.filter(contract=contract))
        form.fields['event'].label = "Evènement"
        form.fields['event'].widget.attrs.update({'class': 'form-control'})
    return render(request,
                  'execution/event_add_livrable.html',
                  {'form': form, 'contract':contract})

@login_required
def create_ordre_service(request, id):
    contract = Contract.objects.get(id=id)
    if request.method == 'POST':
        form = OrdreServiceForm(request.POST)
        if form.is_valid:
            ordre_service = form.save(commit=False)
            ordre_service.authorOs = request.user
            ordre_service.save()
            return redirect('follow-tech-contract', contract.id)
    else:
        form = OrdreServiceForm()
        form.fields['event'] = forms.ModelChoiceField(Event.objects.filter(contract=contract))
        form.fields['event'].label = 'Evènement'
        form.fields['event'].widget.attrs.update({'class': 'form-control'})

    return render(request,
                  'execution/event_add_ordre_service.html',
                  {'form': form, 'contract':contract})

@login_required
def create_avenant(request, id):
    contract = Contract.objects.get(id=id)
    if request.method == 'POST':
        form = AvenantForm(request.POST)
        if form.is_valid:
            avenant = form.save(commit=False)
            avenant.authorAv = request.user
            avenant.save()
            return redirect('follow-tech-contract', contract.id)
    else:
        form = AvenantForm()
        form.fields['event'] = forms.ModelChoiceField(Event.objects.filter(contract=contract))
        form.fields['event'].label = 'Evènement'
        form.fields['event'].widget.attrs.update({'class': 'form-control'})

    return render(request,
                  'execution/event_add_avenant.html',
                  {'form': form, 'contract':contract})

@login_required
def event_detail(request, id):
    event = Event.objects.get(id=id)
    context = {'event': event,
                }
    return render(request, 'execution/event_detail.html', context=context)

@login_required
def create_decompte(request, id):
    contract = Contract.objects.get(id=id)
    if request.method == 'POST':
        form = DecompteForm(request.POST)
        if form.is_valid:
            decompte = form.save(commit=False)
            decompte.contract = contract
            decompte.authorDe = request.user
            decompte.save()
            return redirect('follow-fi-contract', contract.id)
    else:
        form = DecompteForm()

    return render(request,
                  'execution/contract_add_decompte.html',
                  {'form': form, 'contract':contract})

@login_required
def create_paiement(request, id):
    decompte = Decompte.objects.get(id=id)
    contract = decompte.contract
    if request.method == 'POST':
        form = PaiementForm(request.POST)
        if form.is_valid:
            paiement = form.save(commit=False)
            paiement.decompte = decompte
            paiement.authorPa = request.user
            paiement.save()
            return redirect('follow-fi-contract', contract.id)
    else:
        form = PaiementForm()

    return render(request,
                  'execution/contract_add_paiement.html',
                  {'form': form, 'contract':contract})

@login_required
def decompte_detail(request, id):
    decompte = Decompte.objects.get(id=id)
    context = {'decompte': decompte,
                }
    return render(request, 'execution/decompte_detail.html', context=context)

sysmap/execution/templates/execution/contract_add_decompte.html
{% extends 'contracts/base.html' %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800"> AJOUT DECOMPTE DU MARCHE / CONTRAT</h1>
    </div>
    <div class="row"> 
        <div class="col-sm-4">
            {% include "contracts/contract_summary.html" %}
        </div>
        <div class="col-sm-8">         
            <!-- Basic Card Example -->
            <div class="card shadow mb-4">
                <div class="card-body">
                    <h6 class="m-0 font-weight-bold text-primary"> AJOUT DES INFORMATIONS SUR UN DECOMPTE DU MARCHE:</h6>
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="col-sm-2">
                            <button type="submit" class="btn btn-primary btn-block">Enregistrer</button> 
                        </div>
                               
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-sm-2">
    <p>
        <a href="{% url 'contract-detail' contract.id %}" class="btn btn-primary btn-block">Fiche descriptive du contrat</a>
    </p>
</div>

{% endblock %}

sysmap/execution/templates/execution/contract_add_event.html
{% extends 'contracts/base.html' %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="row">
        <div class="col-md-8">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800"> SUIVI DU MARCHE / CONTRAT</h1>
            </div>
        </div>
        <div class="col-sm-2">

        </div>
        <div class="col-sm-2">
            <a href="{% url 'contract-detail' contract.id %}" class="btn btn-primary btn-block">Fiche descriptive du contrat</a>
        </div>
    </div>

    <div class="row"> 
        <div class="col-sm-4">
            {% include "contracts/contract_summary.html" %}
        </div>
        <div class="col-sm-8">         
            <!-- Basic Card Example -->
            <div class="card shadow mb-4">
                <div class="card-body">
                    <form action="" method="POST" novalidate>
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary btn-block">Enregistrer</button>        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

sysmap/execution/templates/execution/contract_add_paiement.html
{% extends 'contracts/base.html' %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800"> AJOUT PAIEMETN DU MARCHE / CONTRAT</h1>
    </div>
    <div class="row"> 
        <div class="col-sm-4">
            {% include "contracts/contract_summary.html" %}
        </div>
        <div class="col-sm-8">         
            <!-- Basic Card Example -->
            <div class="card shadow mb-4">
                <div class="card-body">
                    <h6 class="m-0 font-weight-bold text-primary"> AJOUT DES INFORMATIONS SUR UN PAIEMENT DU MARCHE:</h6>
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="col-sm-2">
                            <button type="submit" class="btn btn-primary btn-block">Enregistrer</button> 
                        </div>
                               
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-sm-2">
    <p>
        <a href="{% url 'contract-detail' contract.id %}" class="btn btn-primary btn-block">Fiche descriptive du contrat</a>
    </p>
</div>

{% endblock %}

sysmap/execution/templates/execution/decompte_detail.html
{% extends 'contracts/base.html' %}

{% block content %}
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Détail du décompte : <span class="text-success">{{ event.libelle }} le {{ event.dateEvent }}</span></h1>
    </div>

    <div class="row">

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                               Livrables</div>
                            <div class="h4 mb-0 font-weight-bold text-gray-800">{{ event.livrable_set.all.count }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Annual) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Ordre de service</div>
                            <div class="h4 mb-0 font-weight-bold text-gray-800">{{ event.ordre_service_set.all.count }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Tasks Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Avenants
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h4 mb-0 mr-3 font-weight-bold text-gray-800">{{ event.avenant_set.all.count }}</div>
                                </div>

                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Pending Requests Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                Objet de contrat</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ event.contract.object }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-lg-4">

            <!-- Dropdown Card Example -->
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#collapseCardExample1" class="d-block card-header py-3" data-toggle="collapse"
                role="button" aria-expanded="true" aria-controls="collapseCardExample">
                <h6 class="m-0 font-weight-bold text-primary">Livrables</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="collapseCardExample1">
                <div class="card-body">
                    {% for livrable in event.livrable_set.all %}
                        <h6> Désignation: <span class="m-0 font-weight-bold text-primary">{{ livrable.libelle }}</span></h6>        
                        <h6> Nature : <span class="m-0 font-weight-bold text-primary">{{ livrable.get_nature_display }}</span></h6>
                        <h6> Type : <span class="m-0 font-weight-bold text-primary">{{ livrable.get_typeLivrable_display }}</span></h6>
                        <h6> Réalisation effective ?: <span class="m-0 font-weight-bold text-primary">{{ livrable.isRealized|yesno }}</span></h6>
                        <h6> Reception effective ?: <span class="m-0 font-weight-bold text-primary">{{ livrable.isReceive|yesno }}</span></h6>
                        <h6> Date de validation: <span class="m-0 font-weight-bold text-primary">{{ livrable.datValidation }}</span></h6>
                        <hr class="sidebar-divider">
                    {% endfor %}
                </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <!-- Collapsable Card Example -->
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#collapseCardExample2" class="d-block card-header py-3" data-toggle="collapse"
                    role="button" aria-expanded="true" aria-controls="collapseCardExample2">
                    <h6 class="m-0 font-weight-bold text-primary">Ordres de Service</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="collapseCardExample2">
                    <div class="card-body">
                    {% for ordre_service in event.ordre_service_set.all %}
                        <h6> Numéro: <span class="m-0 font-weight-bold text-primary">{{ ordre_service.numerOs }}</span></h6>
                        
                        <h6> Motif : <span class="m-0 font-weight-bold text-primary">{{ ordre_service.motifOs }}</span></h6>
                       
                        <h6> Date : <span class="m-0 font-weight-bold text-primary">{{ ordre_service.datOs }}</span></h6>
                        
                        <h6> Type : <span class="m-0 font-weight-bold text-primary">{{ ordre_service.get_typeOs_display }}</span></h6>
                        <hr class="sidebar-divider">
                    {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#collapseCardExample3" class="d-block card-header py-3" data-toggle="collapse"
                    role="button" aria-expanded="true" aria-controls="collapseCardExample3">
                    <h6 class="m-0 font-weight-bold text-primary">Avenants</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="collapseCardExample3">
                    <div class="card-body">
                        {% for avenant in event.avenant_set.all %}
                            <h6> Objet: <span class="m-0 font-weight-bold text-primary">{{ avenant.objetAvenant }}</span></h6>
                            
                            <h6> Date : <span class="m-0 font-weight-bold text-primary">{{ avenant.dateAvenant }}</span></h6>
                            {% if avenant.montant != None %}
                                <h6> Montant : <span class="m-0 font-weight-bold text-primary">{{ avenant.montant }}</span></h6>
                            {% endif %}
                            
                            <hr class="sidebar-divider">
                    {% endfor %}
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}